[build]
  base = "frontend"             # go inside frontend folder
  command = "npm ci && npm run build"   # production build command
  publish = "dist"              

[dev]
  command = "npm run dev"
  port = 5173
